version: '3.8'
services:
  zigbee2mqtt:
    container_name: zigbee2mqtt_zigbee
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    volumes:
      - /home/USER/zigbee:/app/data
      - /run/udev:/run/udev:ro
    network_mode: "host"
    environment:
      - TZ=Europe/London
    devices:
      - /dev/ttyUSB0:/dev/ttyACM0

  mosquitto:
    container_name: zigbee2mqtt_mqtt
    image: eclipse-mosquitto
    network_mode: "host"
    volumes:
      - /home/USER/mqtt/conf:/mosquitto/conf
      - /home/USER/mqtt/data:/mosquitto/data
      - /home/USER/mqtt/log:/mosquitto/log
